# Generated by Django 4.2.7 on 2025-02-08 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalImageGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='games')),
                ('image2', models.ImageField(upload_to='games')),
                ('image3', models.ImageField(upload_to='games')),
                ('image4', models.ImageField(upload_to='games')),
                ('image_1_label', models.CharField(default='', max_length=1000)),
                ('image_2_label', models.CharField(default='', max_length=1000)),
                ('image_3_label', models.CharField(default='', max_length=1000)),
                ('image_4_label', models.CharField(default='', max_length=1000)),
                ('time', models.IntegerField(default=0)),
                ('answer', models.CharField(choices=[('image1', 'image1'), ('image2', 'image2'), ('image3', 'image3'), ('image4', 'image4')], max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=1000)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ImagePuzzle')),
            ],
        ),
        migrations.CreateModel(
            name='NumberIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='games')),
                ('image2', models.ImageField(null=True, upload_to='games')),
                ('image3', models.ImageField(null=True, upload_to='games')),
                ('image4', models.ImageField(null=True, upload_to='games')),
                ('image5', models.ImageField(null=True, upload_to='games')),
                ('image6', models.ImageField(null=True, upload_to='games')),
                ('image_1_label', models.CharField(default='', max_length=1000)),
                ('image_2_label', models.CharField(default='', max_length=1000)),
                ('image_3_label', models.CharField(default='', max_length=1000)),
                ('image_4_label', models.CharField(default='', max_length=1000)),
                ('image_5_label', models.CharField(default='', max_length=1000)),
                ('image_6_label', models.CharField(default='', max_length=1000)),
                ('time', models.IntegerField(default=0)),
                ('answer', models.CharField(choices=[('image1', 'image1'), ('image2', 'image2'), ('image3', 'image3'), ('image4', 'image4'), ('image5', 'image5'), ('image6', 'image6')], max_length=1000)),
            ],
            options={
                'verbose_name': 'Number Identification',
            },
        ),
        migrations.CreateModel(
            name='ObjectIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='games')),
                ('image2', models.ImageField(upload_to='games')),
                ('image3', models.ImageField(upload_to='games')),
                ('image4', models.ImageField(upload_to='games')),
                ('image_1_label', models.CharField(default='', max_length=1000)),
                ('image_2_label', models.CharField(default='', max_length=1000)),
                ('image_3_label', models.CharField(default='', max_length=1000)),
                ('image_4_label', models.CharField(default='', max_length=1000)),
                ('time', models.IntegerField(default=0)),
                ('answer', models.CharField(choices=[('image1', 'image1'), ('image2', 'image2'), ('image3', 'image3'), ('image4', 'image4')], max_length=1000)),
            ],
            options={
                'verbose_name': 'Object Identification',
            },
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(upload_to='images/')),
                ('caption', models.CharField(max_length=300)),
                ('des', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='replay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay', models.CharField(max_length=300)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.comments')),
            ],
        ),
        migrations.CreateModel(
            name='Numbergame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_result', models.CharField(choices=[('win', 'Win'), ('lose', 'Lose')], max_length=10)),
                ('dots', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField()),
                ('count', models.IntegerField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='imagetile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_result', models.CharField(choices=[('win', 'Win'), ('lose', 'Lose')], max_length=10)),
                ('dots', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField()),
                ('count', models.IntegerField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='imagepuzzlegame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_result', models.CharField(choices=[('win', 'Win'), ('lose', 'Lose')], max_length=10)),
                ('dots', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField()),
                ('count', models.IntegerField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='animalgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_result', models.CharField(choices=[('win', 'Win'), ('lose', 'Lose')], max_length=10)),
                ('dots', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField()),
                ('count', models.IntegerField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
