# Generated by Django 5.0.4 on 2025-02-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0002_replay_parent_replay_user_alter_comments_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=300)),
                ("phonenumber", models.IntegerField(blank=True, null=True)),
                ("availabletime", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="replay",
            name="parent",
        ),
    ]
