# Generated by Django 5.0.4 on 2025-02-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0003_doctors_remove_replay_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="availabletime",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
