# Generated by Django 5.0.4 on 2025-02-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0004_alter_doctors_availabletime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="doctors",
            name="availabletime",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="doctors",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
