# Generated by Django 4.2.7 on 2025-02-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_comment_post_remove_replay_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=300, null=True)),
                ('bot', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
