# Generated by Django 4.2.7 on 2025-02-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_chat_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_bot',
            name='user_msg',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
