# Generated by Django 4.2.7 on 2025-02-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_chat_bot_user_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='image',
            field=models.ImageField(null=True, upload_to='imagess/'),
        ),
    ]
