# Generated by Django 4.2.7 on 2025-02-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_doctors_fees_doctors_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='address',
            new_name='hospitalname',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='phonenumber',
        ),
    ]
