# Generated by Django 4.2.7 on 2025-02-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_rename_address_doctors_hospitalname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalgame',
            options={'verbose_name': 'Animalgame Data'},
        ),
        migrations.AlterModelOptions(
            name='imagepuzzlegame',
            options={'verbose_name': 'imagepuzzlegame Data'},
        ),
        migrations.AlterModelOptions(
            name='imagetile',
            options={'verbose_name': 'Imagetile Data'},
        ),
        migrations.AlterModelOptions(
            name='numbergame',
            options={'verbose_name': 'Numbergame Data'},
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='availabletime',
        ),
        migrations.AddField(
            model_name='animalimagegame',
            name='is_visible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='imagepuzzle',
            name='is_visible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='numberidentification',
            name='is_visible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='objectidentification',
            name='is_visible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
