# Generated by Django 4.2.7 on 2025-02-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='questions',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
