# Generated by Django 4.2.7 on 2025-02-27 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_faq_category_alter_faq_answer_alter_faq_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
