# Generated by Django 5.1.1 on 2025-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_videosection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosection',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
